# Generated by Django 4.1.9 on 2023-08-05 19:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuarios_user_description'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('comentario', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Publicaciones',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('fecha_publicacion', models.DateField(default=datetime.date.today)),
                ('imagen', models.CharField(max_length=500)),
                ('contenido', models.CharField(max_length=500)),
                ('preferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.gustos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios')),
            ],
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Publicacion',
        ),
        migrations.AddField(
            model_name='likes',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.publicaciones'),
        ),
        migrations.AddField(
            model_name='likes',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='Publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.publicaciones'),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios'),
        ),
    ]
