# Generated by Django 4.1.9 on 2023-06-27 02:10

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=500)),
                ('correo', models.CharField(max_length=500)),
                ('imagen', models.CharField(max_length=500)),
                ('contrasenna', models.CharField(max_length=500)),
            ],
        ),
    ]
