# Generated by Django 4.1.9 on 2023-07-07 04:06

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_gustos_usuarios_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='GustosUsuarios',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('idGusto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.gustos')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios')),
            ],
        ),
    ]
