# Generated by Django 4.1.9 on 2023-07-11 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_gustosusuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='user_description',
            field=models.CharField(default='new user', max_length=500),
        ),
    ]
