# Generated by Django 4.1.10 on 2023-07-09 05:08

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('id_usuario1', models.CharField(max_length=500)),
                ('id_usuario2', models.CharField(max_length=500)),
            ],
        ),
    ]
