# Generated by Django 4.1.9 on 2023-07-07 03:24

import datetime
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gustos',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('gusto', models.CharField(max_length=500)),
                ('imagen', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='usuarios',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
